# Generated by Django 5.1.1 on 2024-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_remove_student_teacher_alter_student_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(
                related_name="students",
                to="school.teacher",
                verbose_name="Учителя",
            ),
        ),
    ]
